pipelines:
    branches:
      prod:
        - step:
           script:
             - git remote add sync git@github.com:opencelium/opencelium.git
             - git checkout prod
             - git pull    
             - git push sync prod
      dev:
        - step:
           script:
             - git remote add sync git@github.com:opencelium/opencelium.git
             - git checkout dev
             - git pull    
             - git push sync dev