###########################################################################
#                                                                         #
#   Webserver configuration section                                       # 
#                                                                         #
#   Find here the default port configuration of the backend server        #
#   and the ssl configuration.                                            #
#                                                                         #
###########################################################################          
server:
  port: 9090
    # ssl:
    #   enabled: true
    #   key-store-type: PKCS12
    #   key-store: src/main/resources/keystore.p12
    #   key-store-password: root
    #   key-password: root
    #   key-alias: tomcat

###########################################################################
#                                                                         #
#   Database configuration section of MariaDB and Neo4j                   # 
#                                                                         #
###########################################################################
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/opencelium?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
    username: root
    password: root
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver
  neo4j:
    url: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret1234
###########################################################################
#                                                                         #
#   Mail configuration section                                            #
#                                                                         #
###########################################################################
  mail:
    opencelium:
      from: noreply@opencelium.io
  #    enabled: false
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  #        ssl:
  #          trust: example.host.de
###########################################################################
#                                                                         #
#   Configuration of third part tools                                     #
#                                                                         #
###########################################################################
#  ldap:
#    embedded:
#      base-dn: dc=springframework,dc=org
#      ldif: classpath:test-server.ldif
#      port: 8389
#      url: ldap://localhost:8389/
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
###########################################################################
#                                                                         #
#   Basic configuration section. Do not change the following              #
#   configuration.                                                        #
#                                                                         #
###########################################################################
  main:
    banner-mode: "off"
  data:
    rest:
      basePath: /api
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      dll-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1000000KB
      max-request-size: 1000000KB
  http:
    multipart:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          jobStore:
            tablePrefix: QRTZ_
    job-store-type: jdbc
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    path: /docs
    supportedSubmitMethods:
      - get
      - put
      - post
      - delete
      - options
      - head
      - patch
      - trace
    tagsSorter: alpha
    open-api-custom-settings:
      extensions:
        x-links-enabled: false
  default-produces-media-type: application/json

logging:
  file: src/main/resources/logs
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework:
        data:
          neo4j: OFF

management:
  health:
    defaults:
      enabled: false
    status:
      http-mapping:
        DOWN: 200
        UP: 200
  endpoint:
    health:
      show-details: always

opencelium:
  version: 3.2
  debug_mode: true
  reboot:
    path: src/backend/src/main/resources/bashfile/restart.sh
  token:
    secret: becon.opencelium
    activity-time: 18000
    experation-time: 86400
  assistant:
    update:
      online:
        url: { insert url where portal service is located }
  notification:
    tools:
      slack:
        webhook: https://hooks.slack.com/services/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
      teams:
        grant_type: refresh_token
        client_id: a88b0cb6-8026-44af-ab6c-3f144605a4a2
        client_secret: mux7Q~61v3jA7cLt2wJTe9GiE039ynXHd4VRH
        refresh_token: 0.ASAACGT_xLM3Oku76wQUrsfO77YMi6gmgK9Eq2w_FEYFpKLkABY.AgABAAEAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P9c--5CRqd-2-AQGtnnNPIiXTGSIbrpVXGip3CbQYaaGOZUOjOe_wiMJvI3BD3N7p7ODMdXDKnKs_tRZiC9j8mkCpHga6owr-6f6rfo46rBuSmTAbuHic4icWhopX0r2VYFBtxK0xHxiDaAAclRw7XV9qrABkZ7aHhTzfmySFlUR7oj_ih1WbtohhGAknvlyvLlwEGXdVMQwmY-w1AqB5ikdFIw4CPW5jI2YWXcQPlCV0HWqNin27E-PhuzCsmUizh5s9F-2DYonJAlmdAjC2TMPYuUGBu8gIUzdRYUH90YI0cEWTUJfGgIP3xLZj7TQ9UByK5L4SjhTWyFtHN6xFX4QwlG_7hG-3E9sBkEOP_j_PldEes6Lj3eNJ-crBHm2I0PPeoFWgQINxSGdEcWnMC82G2Ntkyo5ETG1uhCGScaxLe76QKXSvqP-DMzz8GM3oQy4BZUpx4BSTUQlSrrjTJuL7wtQoU_fXj6ORqRoKiTrfaP9KIkhGZ2s3CWvUMY8hWuw3xMgl_NaUICuT1FCTw_t5OVwZW-ZV12tlVm812Ywj-yUYrYSs8yg12DQ3saMf53vzLNPJFOhcrodvK4uDSiQj-rmDyUvDqPwPlQphp31BWyvm_j_6glpGTtXBMUWDueojfSwc3bFtuaTy4oCjDw-1u-0QVyBO-jsuC_kkTac0QeEMqsEtP3pUPvr4c7jtnkIx68095ZDCkLwKp6uxWr2aqNIVwlar2KMba0163jKOjHp4za7XmYnB1OOGi-9sXvCEaDgpyV
        tenant: c4ff6408-37b3-4b3a-bbeb-0414aec7ceef
        channel: 19:6e82d697a36c49e8964b1295dc1f401f@thread.tacv2
        teams: 48db6be0-4e1e-494a-a20e-83955faa1a90
#        token: token
#  rest_template:
#      proxy:
#        host: 127.0.0.1
#        port: 8082
