###########################################################################
#                                                                         #
#   Webserver configuration section                                       # 
#                                                                         #
#   Find here the default port configuration of the backend server        #
#   and the ssl configuration.                                            #
#                                                                         #
###########################################################################          
server:
  port: 9090
    # ssl:
    #   enabled: true
    #   key-store-type: PKCS12
    #   key-store: src/main/resources/keystore.p12
    #   key-store-password: root
    #   key-password: root
    #   key-alias: tomcat

###########################################################################
#                                                                         #
#   Database configuration section of MariaDB and Neo4j                   # 
#                                                                         #
###########################################################################
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/opencelium?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
    username: root
    password: root
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver
  neo4j:
    url: bolt://localhost:7687
    authentication:
      username: neo4j
      password: secret1234
###########################################################################
#                                                                         #
#   Mail configuration section                                            #
#                                                                         #
###########################################################################
  mail:
    opencelium:
      from: noreply@opencelium.io
  #    enabled: false
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  #        ssl:
  #          trust: example.host.de
###########################################################################
#                                                                         #
#   Configuration of third part tools                                     #
#                                                                         #
###########################################################################
#  ldap:
#    embedded:
#      base-dn: dc=springframework,dc=org
#      ldif: classpath:test-server.ldif
#      port: 8389
#      url: ldap://localhost:8389/
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
###########################################################################
#                                                                         #
#   Basic configuration section. Do not change the following              #
#   configuration.                                                        #
#                                                                         #
###########################################################################
  main:
    banner-mode: "off"
  data:
    rest:
      basePath: /api
  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      dll-auto: validate
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1000000KB
      max-request-size: 1000000KB
  http:
    multipart:
      enabled: false
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          jobStore:
            tablePrefix: QRTZ_
    job-store-type: jdbc
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

springdoc:
  swagger-ui:
    path: /docs
    supportedSubmitMethods:
      - get
      - put
      - post
      - delete
      - options
      - head
      - patch
      - trace
    tagsSorter: alpha
    open-api-custom-settings:
      extensions:
        x-links-enabled: false
  default-produces-media-type: application/json

logging:
  file: src/main/resources/logs
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    org:
      springframework:
        data:
          neo4j: OFF

management:
  health:
    defaults:
      enabled: false
    status:
      http-mapping:
        DOWN: 200
        UP: 200
  endpoint:
    health:
      show-details: always

opencelium:
  version: 3.1.2
  debug_mode: true
  reboot:
    path: src/backend/src/main/resources/bashfile/restart.sh
  token:
    secret: becon.opencelium
    activity-time: 18000
    experation-time: 86400
  assistant:
    update:
      online:
        url: { insert url where portal service is located }
#  rest_template:
#      proxy:
#        host: 127.0.0.1
#        port: 8082
