spring:
  main:
    banner-mode: "off"

  data:
    rest:
      basePath: /api
    neo4j:
      url: bolt://localhost:7687
      username: neo4j
      password: secret

  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false

    hebirnate:
      dll-auto: validate

  datasource:
    url: jdbc:mariadb://localhost:3306/opencelium?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
    username: root
    password: root
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10240KB
      max-request-size: 10240KB

  http:
    multipart:
      enabled: false

  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          jobStore:
            tablePrefix: QRTZ_
    job-store-type: jdbc

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: uname
    password: password
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  #        socketFactory:
  #          port: 465
  #          class: javax.net.ssl.SSLSocketFactory

server:
  port: 9090

management:
  health:
    status:
      http-mapping:
        DOWN: 200
        UP: 200
  endpoint:
    health:
      show-details: always

elasticsearch:
  clustername: open_celium
  host: localhost
  port: 9300

opencelium:
  version: 1.3
  mail:
    from: OC_Application
  token:
    secret: any_secret_key
    activity-time: 18000
    experation-time: 86400


#  ldap:
#    embedded:
#      base-dn: dc=springframework,dc=org
#      ldif: classpath:test-server.ldif
#      port: 8389
#      url: ldap://localhost:8389/
