spring:
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest

  main:
    banner-mode: "off"

  data:
    rest:
      basePath: /api
    neo4j:
      url: bolt://localhost:7687
      username: neo4j
      password: secret

  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false

    hibernate:
      dll-auto: validate

  datasource:
    url: jdbc:mariadb://localhost:3306/opencelium?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Berlin
    username: root
    password: root
    initialization-mode: always
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 1000000KB
      max-request-size: 1000000KB

  http:
    multipart:
      enabled: false

  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          jobStore:
            tablePrefix: QRTZ_
    job-store-type: jdbc

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: uname
    password: password
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
  #        socketFactory:
  #          port: 465
  #          class: javax.net.ssl.SSLSocketFactory

server:
  port: 9090
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore/keystore.p12
#    key-store-password: password
#    key-password: password
#    key-alias: tomcat

management:
  health:
    defaults:
      enabled: false
    status:
      http-mapping:
        DOWN: 200
        UP: 200
  endpoint:
    health:
      show-details: always

elasticsearch:
  clustername: open_celium
  host: localhost
  port: 9300

kibana:
  host: localhost
  port: 5601

opencelium:
  version: 3.0.0
  debug_mode: false
  reboot:
    path: src/backend/src/main/resources/bashfile/restart.sh
  mail:
    from: OC_Application
  token:
    secret: becon.opencelium
    activity-time: 18000
    experation-time: 86400
  assistant:
    repo:
      url: https://bobmustaev@bitbucket.org/becon_gmbh/opencelium



#  ldap:
#    embedded:
#      base-dn: dc=springframework,dc=org
#      ldif: classpath:test-server.ldif
#      port: 8389
#      url: ldap://localhost:8389/