# operations: add, modify, delete, rename.
versions:
  - version: 4.0
    changes:
      - changeset: 1
        operation: add
        value: 4.0
        path: opencelium.version
      - changeset: 2
        operation: add
        value: mongodb://oc_admin:secretsecret@localhost:27017/opencelium
        path: spring.data.mongodb.uri
      - changeset: 3
        operation: delete
        path: spring.neo4j
      - changeset: 4
        operation: delete
        path: opencelium.notification.tools.teams
      - changeset: 5
        operation: delete
        path: opencelium.reboot
      - changeset: 6
        operation: add
        value: sources
        path: opencelium.installation.type
  - version: 4.1
    changes:
      - changeset: 1
        operation: add
        value: 4.1
        path: opencelium.version
      - changeset: 2
        operation: add
        value: 84bbce3d33de467b47b7e76c2563769!3f9aff968def8ef2674856f67ae8a93f
        path: opencelium.token.secret
