# operations: add, modify, delete, rename, move.
versions:
  - version: 4.0
    changes:
      - changeset: 1
        operation: add
        value: 4.0
        path: opencelium.version
      - changeset: 2
        operation: add
        value: mongodb://oc_admin:secretsecret@localhost:27017/opencelium
        path: spring.data.mongodb.uri
      - changeset: 3
        operation: delete
        path: spring.neo4j
      - changeset: 4
        operation: delete
        path: opencelium.notification.tools.teams
      - changeset: 5
        operation: delete
        path: opencelium.reboot
      - changeset: 6
        operation: add
        value: sources
        path: opencelium.installation.type
  - version: 4.1
    changes:
      - changeset: 1
        operation: add
        value: 4.1
        path: opencelium.version
      - changeset: 2
        operation: add
        value: 84bbce3d33de467b47b7e76c2563769!3f9aff968def8ef2674856f67ae8a93f
        path: opencelium.token.secret
  - version: 4.2
    changes:
      - changeset: 1
        operation: add
        value: 4.2
        path: opencelium.version
      - changeset: 2
        operation: add
        value: https://api.serviceportal.com
        path: opencelium.service_portal.base_url
      - changeset: 3
        operation: add
        value: your-token-here
        path: opencelium.service_portal.token
      - changeset: 4
        operation: add
        value: OFF
        path: logging.level.org.springframework.data.ldap
  - version: 4.3
    changes:
      - changeset: 1
        operation: add
        value: 4.3
        path: opencelium.version
  - version: 4.4
    changes:
      - changeset: 1
        operation: add
        value: 4.4
        path: opencelium.version
  - version: 4.5
    changes:
      - changeset: 1
        operation: add
        value: 4.5
        path: opencelium.version
      - changeset: 2
        operation: add
        value: https://service.opencelium.io
        path: opencelium.service_portal.base_url
      - changeset: 3
        operation: add
        value: "127.0.0.1"
        path: server.address
      - changeset: 4
        operation: add
        value: /websocket
        path: websocket.endpoint
      - changeset: 5
        operation: add
        value: '-'
        path: opencelium.online_services.invoker_sync.time
      - changeset: 6
        operation: add
        value: false
        path: opencelium.online_services.invoker_sync.active
      - changeset: 7
        operation: add
        value: '-'
        path: opencelium.online_services.template_sync.time
      - changeset: 8
        operation: add
        value: false
        path: opencelium.online_services.template_sync.active
  - version: 4.5.1
    changes:
      - changeset: 1
        operation: add
        value: 4.5.1
        path: opencelium.version
      - changeset: 2
        operation: add
        value: password
        path: opencelium.connector.master_password
      - changeset: 3
        operation: add
        value: false
        path: opencelium.online_services.active
  - version: 4.6
    changes:
      - changeset: 1
        operation: add
        value: 4.6
        path: opencelium.version
      - changeset: 2
        operation: rename
        value: base-url
        path: opencelium.service_portal.base_url
      - changeset: 3
        operation: rename
        value: service-portal
        path: opencelium.service_portal
      - changeset: 4
        operation: rename
        value: master-password
        path: opencelium.connector.master_password
      - changeset: 5
        operation: rename
        value: template-sync
        path: opencelium.online_services.template_sync
      - changeset: 6
        operation: rename
        value: online-services
        path: opencelium.online_services
      - changeset: 7
        operation: rename
        value: incoming-webhook
        path: opencelium.notification.tools.incoming_webhook
      - changeset: 8
        operation: rename
        value: debug-mode
        path: opencelium.debug_mode
      - changeset: 9
        operation: modify
        value: ./support-files
        path: opencelium.support.file.directory
      - changeset: 10
        operation: move
        value: management.endpoint.health.status
        path: management.health.status