versions:
  - version: 4.0aa
    changes:
      - changeset: 1
        operation: add
        value: 4.0
        path: opencelium.version
      - changeset: 2
        operation: add
        value: mongodb://oc_admin:secretsecret@localhost:27017/opencelium
        path: spring.data.mongodb.uri
