server {
        listen 80;
        listen [::]:80;

	server_tokens off;
	add_header X-Frame-Options sameorigin;
	return 301 https://$host$request_uri;

}

server {
        # SSL configuration
        
        listen 443 ssl;
        listen [::]:443 ssl;

	ssl_certificate /etc/ssl/certs/opencelium.pem;
	ssl_certificate_key /etc/ssl/private/opencelium.key;

        root /opt/opencelium/src/frontend;

        index index.html;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri /index.html;
        }
        
        # Activate Proxy
        location /api/ {

                # Routing of all requests to /api to the backend server
                proxy_pass http://localhost:9090/;
                client_max_body_size 200M;

                #Set proxy header
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_set_header X-Master-Password $http_x_master_password;
		proxy_set_header X-Forwarded-Proto https;

                # Optional: CORS headers
                add_header Access-Control-Allow-Origin "*";
                add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
                add_header Access-Control-Allow-Headers "Content-Type, Authorization";

                # Handle preflight requests
                if ($request_method = OPTIONS) {
                    add_header Content-Length 0;
                    add_header Content-Type text/plain;
                    return 204;
                }
        }

        # Activate proxy for websocket
        location /ws/ {
                proxy_pass http://localhost:9090/ws/;
                proxy_http_version 1.1;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";

                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }	
	
}
