-- MySQL Script generated by MySQL Workbench
-- Fri Nov 29 14:19:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opencelium
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `opencelium` ;

-- -----------------------------------------------------
-- Schema opencelium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opencelium` DEFAULT CHARACTER SET utf8 ;
USE `opencelium` ;

-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_JOB_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_JOB_DETAILS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_JOB_DETAILS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `JOB_NAME` VARCHAR(190) NOT NULL,
  `JOB_GROUP` VARCHAR(190) NOT NULL,
  `DESCRIPTION` VARCHAR(250) NULL DEFAULT NULL,
  `JOB_CLASS_NAME` VARCHAR(250) NOT NULL,
  `IS_DURABLE` VARCHAR(1) NOT NULL,
  `IS_NONCONCURRENT` VARCHAR(1) NOT NULL,
  `IS_UPDATE_DATA` VARCHAR(1) NOT NULL,
  `REQUESTS_RECOVERY` VARCHAR(1) NOT NULL,
  `JOB_DATA` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
  INDEX `IDX_QRTZ_J_REQ_RECOVERY` (`SCHED_NAME` ASC, `REQUESTS_RECOVERY` ASC),
  INDEX `IDX_QRTZ_J_GRP` (`SCHED_NAME` ASC, `JOB_GROUP` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_TRIGGERS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_TRIGGERS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  `JOB_NAME` VARCHAR(190) NOT NULL,
  `JOB_GROUP` VARCHAR(190) NOT NULL,
  `DESCRIPTION` VARCHAR(250) NULL DEFAULT NULL,
  `NEXT_FIRE_TIME` BIGINT(13) NULL DEFAULT NULL,
  `PREV_FIRE_TIME` BIGINT(13) NULL DEFAULT NULL,
  `PRIORITY` INT(11) NULL DEFAULT NULL,
  `TRIGGER_STATE` VARCHAR(16) NOT NULL,
  `TRIGGER_TYPE` VARCHAR(8) NOT NULL,
  `START_TIME` BIGINT(13) NOT NULL,
  `END_TIME` BIGINT(13) NULL DEFAULT NULL,
  `CALENDAR_NAME` VARCHAR(190) NULL DEFAULT NULL,
  `MISFIRE_INSTR` SMALLINT(2) NULL DEFAULT NULL,
  `JOB_DATA` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
  INDEX `IDX_QRTZ_T_J` (`SCHED_NAME` ASC, `JOB_NAME` ASC, `JOB_GROUP` ASC),
  INDEX `IDX_QRTZ_T_JG` (`SCHED_NAME` ASC, `JOB_GROUP` ASC),
  INDEX `IDX_QRTZ_T_C` (`SCHED_NAME` ASC, `CALENDAR_NAME` ASC),
  INDEX `IDX_QRTZ_T_G` (`SCHED_NAME` ASC, `TRIGGER_GROUP` ASC),
  INDEX `IDX_QRTZ_T_STATE` (`SCHED_NAME` ASC, `TRIGGER_STATE` ASC),
  INDEX `IDX_QRTZ_T_N_STATE` (`SCHED_NAME` ASC, `TRIGGER_NAME` ASC, `TRIGGER_GROUP` ASC, `TRIGGER_STATE` ASC),
  INDEX `IDX_QRTZ_T_N_G_STATE` (`SCHED_NAME` ASC, `TRIGGER_GROUP` ASC, `TRIGGER_STATE` ASC),
  INDEX `IDX_QRTZ_T_NEXT_FIRE_TIME` (`SCHED_NAME` ASC, `NEXT_FIRE_TIME` ASC),
  INDEX `IDX_QRTZ_T_NFT_ST` (`SCHED_NAME` ASC, `TRIGGER_STATE` ASC, `NEXT_FIRE_TIME` ASC),
  INDEX `IDX_QRTZ_T_NFT_MISFIRE` (`SCHED_NAME` ASC, `MISFIRE_INSTR` ASC, `NEXT_FIRE_TIME` ASC),
  INDEX `IDX_QRTZ_T_NFT_ST_MISFIRE` (`SCHED_NAME` ASC, `MISFIRE_INSTR` ASC, `NEXT_FIRE_TIME` ASC, `TRIGGER_STATE` ASC),
  INDEX `IDX_QRTZ_T_NFT_ST_MISFIRE_GRP` (`SCHED_NAME` ASC, `MISFIRE_INSTR` ASC, `NEXT_FIRE_TIME` ASC, `TRIGGER_GROUP` ASC, `TRIGGER_STATE` ASC),
  CONSTRAINT `qrtz_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `JOB_NAME` , `JOB_GROUP`)
    REFERENCES `opencelium`.`QRTZ_JOB_DETAILS` (`SCHED_NAME` , `JOB_NAME` , `JOB_GROUP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_BLOB_TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_BLOB_TRIGGERS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_BLOB_TRIGGERS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  `BLOB_DATA` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
  INDEX `SCHED_NAME` (`SCHED_NAME` ASC, `TRIGGER_NAME` ASC, `TRIGGER_GROUP` ASC),
  CONSTRAINT `qrtz_blob_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `opencelium`.`QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_CALENDARS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_CALENDARS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_CALENDARS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `CALENDAR_NAME` VARCHAR(190) NOT NULL,
  `CALENDAR` BLOB NOT NULL,
  PRIMARY KEY (`SCHED_NAME`, `CALENDAR_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_CRON_TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_CRON_TRIGGERS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_CRON_TRIGGERS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  `CRON_EXPRESSION` VARCHAR(120) NOT NULL,
  `TIME_ZONE_ID` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
  CONSTRAINT `qrtz_cron_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `opencelium`.`QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_FIRED_TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_FIRED_TRIGGERS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_FIRED_TRIGGERS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `ENTRY_ID` VARCHAR(95) NOT NULL,
  `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  `INSTANCE_NAME` VARCHAR(190) NOT NULL,
  `FIRED_TIME` BIGINT(13) NOT NULL,
  `SCHED_TIME` BIGINT(13) NOT NULL,
  `PRIORITY` INT(11) NOT NULL,
  `STATE` VARCHAR(16) NOT NULL,
  `JOB_NAME` VARCHAR(190) NULL DEFAULT NULL,
  `JOB_GROUP` VARCHAR(190) NULL DEFAULT NULL,
  `IS_NONCONCURRENT` VARCHAR(1) NULL DEFAULT NULL,
  `REQUESTS_RECOVERY` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`, `ENTRY_ID`),
  INDEX `IDX_QRTZ_FT_TRIG_INST_NAME` (`SCHED_NAME` ASC, `INSTANCE_NAME` ASC),
  INDEX `IDX_QRTZ_FT_INST_JOB_REQ_RCVRY` (`SCHED_NAME` ASC, `INSTANCE_NAME` ASC, `REQUESTS_RECOVERY` ASC),
  INDEX `IDX_QRTZ_FT_J_G` (`SCHED_NAME` ASC, `JOB_NAME` ASC, `JOB_GROUP` ASC),
  INDEX `IDX_QRTZ_FT_JG` (`SCHED_NAME` ASC, `JOB_GROUP` ASC),
  INDEX `IDX_QRTZ_FT_T_G` (`SCHED_NAME` ASC, `TRIGGER_NAME` ASC, `TRIGGER_GROUP` ASC),
  INDEX `IDX_QRTZ_FT_TG` (`SCHED_NAME` ASC, `TRIGGER_GROUP` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_LOCKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_LOCKS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_LOCKS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `LOCK_NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`, `LOCK_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_PAUSED_TRIGGER_GRPS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_PAUSED_TRIGGER_GRPS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_PAUSED_TRIGGER_GRPS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`, `TRIGGER_GROUP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_SCHEDULER_STATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_SCHEDULER_STATE` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_SCHEDULER_STATE` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `INSTANCE_NAME` VARCHAR(190) NOT NULL,
  `LAST_CHECKIN_TIME` BIGINT(13) NOT NULL,
  `CHECKIN_INTERVAL` BIGINT(13) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`, `INSTANCE_NAME`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_SIMPLE_TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_SIMPLE_TRIGGERS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_SIMPLE_TRIGGERS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  `REPEAT_COUNT` BIGINT(7) NOT NULL,
  `REPEAT_INTERVAL` BIGINT(12) NOT NULL,
  `TIMES_TRIGGERED` BIGINT(10) NOT NULL,
  PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
  CONSTRAINT `qrtz_simple_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `opencelium`.`QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`QRTZ_SIMPROP_TRIGGERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`QRTZ_SIMPROP_TRIGGERS` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`QRTZ_SIMPROP_TRIGGERS` (
  `SCHED_NAME` VARCHAR(120) NOT NULL,
  `TRIGGER_NAME` VARCHAR(190) NOT NULL,
  `TRIGGER_GROUP` VARCHAR(190) NOT NULL,
  `STR_PROP_1` VARCHAR(512) NULL DEFAULT NULL,
  `STR_PROP_2` VARCHAR(512) NULL DEFAULT NULL,
  `STR_PROP_3` VARCHAR(512) NULL DEFAULT NULL,
  `INT_PROP_1` INT(11) NULL DEFAULT NULL,
  `INT_PROP_2` INT(11) NULL DEFAULT NULL,
  `LONG_PROP_1` BIGINT(20) NULL DEFAULT NULL,
  `LONG_PROP_2` BIGINT(20) NULL DEFAULT NULL,
  `DEC_PROP_1` DECIMAL(13,4) NULL DEFAULT NULL,
  `DEC_PROP_2` DECIMAL(13,4) NULL DEFAULT NULL,
  `BOOL_PROP_1` VARCHAR(1) NULL DEFAULT NULL,
  `BOOL_PROP_2` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
  CONSTRAINT `qrtz_simprop_triggers_ibfk_1`
    FOREIGN KEY (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`)
    REFERENCES `opencelium`.`QRTZ_TRIGGERS` (`SCHED_NAME` , `TRIGGER_NAME` , `TRIGGER_GROUP`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`role` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `icon` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`user` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `email`, `role_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `unique_id_UNIQUE` (`email` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `opencelium`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`activity` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`activity` (
  `user_id` INT(11) NOT NULL,
  `token_id` VARCHAR(45) NULL DEFAULT NULL,
  `request_time` TIMESTAMP NULL DEFAULT NULL,
  `is_locked` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_activity_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opencelium`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`component` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`component` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`connector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`connector` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`connector` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `invoker` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(2048) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`connection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`connection` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`connection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `description` VARCHAR(512) NULL,
  `from_connector_id` INT NULL,
  `to_connector_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencelium`.`enhancement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`enhancement` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`enhancement` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `connection_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `expert_code` VARCHAR(1024) NULL DEFAULT NULL,
  `simple_code` VARCHAR(1024) NULL DEFAULT NULL,
  `language` VARCHAR(45) NULL DEFAULT NULL,
  `expert_var` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `connection_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_enhancement_connection1_idx` (`connection_id` ASC),
  CONSTRAINT `fk_enhancement_connection1`
    FOREIGN KEY (`connection_id`)
    REFERENCES `opencelium`.`connection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 175
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`scheduler`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`scheduler` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`scheduler` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `connection_id` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT(4) NOT NULL,
  `cron_exp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `connection_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_scheduler_connection1_idx` (`connection_id` ASC),
  CONSTRAINT `fk_scheduler_connection1`
    FOREIGN KEY (`connection_id`)
    REFERENCES `opencelium`.`connection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 38
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`execution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`execution` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`execution` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `scheduler_id` INT(11) NOT NULL,
  `ta_id` BIGINT(20) NULL,
  `req_type` VARCHAR(45) NULL DEFAULT NULL,
  `start_time` TIMESTAMP NULL DEFAULT NULL,
  `end_time` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `scheduler_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_execution_scheduler1_idx` (`scheduler_id` ASC),
  CONSTRAINT `fk_execution_scheduler1`
    FOREIGN KEY (`scheduler_id`)
    REFERENCES `opencelium`.`scheduler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`last_execution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`last_execution` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`last_execution` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `scheduler_id` INT(11) NOT NULL,
  `s_start_time` TIMESTAMP NULL DEFAULT NULL,
  `s_end_time` TIMESTAMP NULL DEFAULT NULL,
  `s_duration` BIGINT(20) NULL DEFAULT NULL,
  `s_ta_id` BIGINT(20) NULL DEFAULT NULL,
  `f_start_time` TIMESTAMP NULL DEFAULT NULL,
  `f_end_time` TIMESTAMP NULL DEFAULT NULL,
  `f_duration` BIGINT(20) NULL DEFAULT NULL,
  `f_ta_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `scheduler_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_last_execution_scheduler1_idx` (`scheduler_id` ASC),
  CONSTRAINT `fk_last_execution_scheduler1`
    FOREIGN KEY (`scheduler_id`)
    REFERENCES `opencelium`.`scheduler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`periodicity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`periodicity` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`periodicity` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`permission` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`permission` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`detail` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`detail` (
  `user_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(10) NULL DEFAULT NULL,
  `department` VARCHAR(45) NULL DEFAULT NULL,
  `organisation` VARCHAR(45) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL DEFAULT NULL,
  `profile_picture` VARCHAR(192) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `fk_user_detail_user1_idx` (),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_detail_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `opencelium`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`webhook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`webhook` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`webhook` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `scheduler_id` INT(11) NOT NULL,
  `uuid` VARCHAR(45) NOT NULL,
  `token` VARCHAR(512) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `scheduler_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC),
  INDEX `fk_webhook_scheduler1_idx` (`scheduler_id` ASC),
  CONSTRAINT `fk_webhook_scheduler1`
    FOREIGN KEY (`scheduler_id`)
    REFERENCES `opencelium`.`scheduler` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`role_has_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`role_has_permission` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`role_has_permission` (
  `role_id` INT(11) NOT NULL,
  `component_id` INT(11) NOT NULL,
  `permission_id` INT(11) NOT NULL,
  PRIMARY KEY (`role_id`, `component_id`, `permission_id`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_id` ASC),
  INDEX `fk_role_has_permission_role1_idx` (`role_id` ASC),
  INDEX `fk_role_has_permission_component1_idx` (`component_id` ASC),
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `opencelium`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_id`)
    REFERENCES `opencelium`.`permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_has_permission_component1`
    FOREIGN KEY (`component_id`)
    REFERENCES `opencelium`.`component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `opencelium`.`request_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`request_data` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`request_data` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `connector_id` INT(11) NOT NULL,
  `field` VARCHAR(45) NULL,
  `value` VARCHAR(255) NULL,
  `hidden` TINYINT NULL,
  PRIMARY KEY (`id`, `connector_id`),
  INDEX `fk_data_connector1_idx` (`connector_id` ASC),
  CONSTRAINT `fk_data_connector1`
    FOREIGN KEY (`connector_id`)
    REFERENCES `opencelium`.`connector` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opencelium`.`tamplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opencelium`.`tamplate` ;

CREATE TABLE IF NOT EXISTS `opencelium`.`tamplate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NULL,
  `from_invoker` VARCHAR(70) NULL,
  `to_invoker` VARCHAR(70) NULL,
  `scheme` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
