import {
    basicsContentData
} from "@change_component/form_elements/form_connection/form_svg/layouts/button_panel/help_block/content/data";

export const HelpBlockData: any = [
    {"nodeId":null,"connectionId":null,"title":"title","description":"","fromConnector":{"nodeId":null,"connectorId":2,"title":null,"invoker":{"name":"trello"},"methods":[{"name":"GetBoardList","request":{"endpoint":"{url}/1/boards/{BOARDID}/lists?key={key}&token={token}","body":null,"method":"GET","header":{"Content-Type":"application/json"}},"response":{"success":{"status":"200","body":{"type":"array","format":"json","data":"raw","fields":{"subscribed":"","idBoard":"","pos":"","name":"","closed":"","id":"","softLimit":""}}},"fail":{"status":"400","body":null}},"index":"0","color":"#FFCFB5"}],"operators":[]},"toConnector":{"nodeId":null,"connectorId":2,"title":null,"invoker":{"name":"trello"},"methods":[],"operators":[]},"fieldBinding":[]},
    {"nodeId":null,"connectionId":null,"title":"title2","description":"desc","fromConnector":{"nodeId":null,"connectorId":2,"title":null,"invoker":{"name":"trello"},"methods":[{"name":"GetBoards","request":{"endpoint":"{url}/1/members/{username}/boards?key={key}&token={token}","body":null,"method":"GET","header":{"Content-Type":"application/json"}},"response":{"success":{"status":"200","body":{"type":"array","format":"json","data":"raw","fields":{"name":"","id":""}}},"fail":{"status":"401","body":null}},"index":"0","color":"#FFCFB5"},{"name":"GetLabelsList","request":{"endpoint":"{url}/1/boards/{BOARDID}/labels?key={key}&token={token}","body":null,"method":"GET","header":{"Content-Type":"application/json"}},"response":{"success":{"status":"200","body":{"type":"array","format":"json","data":"raw","fields":{"idBoard":"","color":"","name":"","id":""}}},"fail":{"status":"400","body":null}},"index":"1","color":"#C77E7E"},{"name":"GetBoardCards","request":{"endpoint":"{url}/1/boards/{BoardID}/cards?key={key}&token={token}","body":null,"method":"GET","header":{"Content-Type":"application/json"}},"response":{"success":{"status":"200","body":{"type":"array","format":"json","data":"raw","fields":{"badges":{"comments":""},"shortUrl":"","name":"","dateLastActivity":"","id":"","desc":"","labels":[{"idBoard":"","color":"","name":"","id":""}]}}},"fail":{"status":"400","body":null}},"index":"2","color":"#6477AB"}],"operators":[]},"toConnector":{"nodeId":null,"connectorId":2,"title":null,"invoker":{"name":"trello"},"methods":[{"name":"GetBoardCards","request":{"endpoint":"{url}/1/boards/{BoardID}/cards?key={key}&token={token}","body":null,"method":"GET","header":{"Content-Type":"application/json"}},"response":{"success":{"status":"200","body":{"type":"array","format":"json","data":"raw","fields":{"badges":{"comments":""},"shortUrl":"","name":"","dateLastActivity":"","id":"","desc":"","labels":[{"idBoard":"","color":"","name":"","id":""}]}}},"fail":{"status":"400","body":null}},"index":"0","color":"#98BEC7"},{"name":"SearchInBoard","request":{"endpoint":"{url}/1/search?idBoard={BOARDID}&key={key}&token={token}&query={QUERY}","body":null,"method":"GET","header":{"Content-Type":"application/json"}},"response":{"success":{"status":"200","body":{"type":"object","format":"json","data":"raw","fields":{"cards":[{"name":"","id":""}]}}},"fail":{"status":"401","body":null}},"index":"1","color":"#9EC798"}],"operators":[]},"fieldBinding":[]}
];

export const HelpBlockAllData: any = {};

for(let i = 0; i < basicsContentData.length; i++){
    HelpBlockAllData[basicsContentData[i].animationName] = HelpBlockData[i];
}
